language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: IgoSCzMvuZnAHUfVjYzd3qd1ct7EdADohe1hQHBAyxdUfj/k4n5AW6qnDlV7jPfDSFJ89OALuVRliWhjv5GBodCwc9zOSxMfikG54A689lC9HtRXZOANmj09AL8oxs0idndE05iAivdFUrVIuqeC7DsQ8Kq0WHSHuBGcAlbxCKZxf9+U0a/Yrt36hVEuR9NMkW/zuwJTjLV3sGaL7BjWGCH7R4HnHz1b5teozuP1n1OE09zFi2592raNU87Y4TMx5EFVM70K9cgD9buJoGGM3Xp4hu3z/S+X5NBAIjMRuPreUTwYxR9Us+kLBFsfohnL+tbfozqMF7YHT2fa1VBBhzwf57Y3/XcuJKrXvoW+71PWmJ9CvLIktUwpoGdJZOp7dnWFLySCXg3zWrnv9PYtU0C0vFlUU/IHQbtAsY+/kd4DQyIwg09axCo1HQzSNK5gYzx+QyIBDSGK3QAEVjuGl3UVmhRFv+S2tZ5eL2rjY+cGXtDa9S7qL7JzK1juY+toNG1RqkAbIX41KQ4KQeUQIkkCjoIus5Aj2P1vezaAalZjzCwTVUnZAFVRtMO1tON+5lwCUfV5D9eMusOw9M88T2DgPh1uV6jUeSZBcAPRd7/57o3YpsHPQ09PwhvQXk6IgxiGkLkhobqIQsXPQmP46TEi+jFq3FTaHafWyi1CGJ0=
  app: node-capstone-csr
  on:
    repo: Chrolan/node-capstone-csr
