language: node_js
node_js: node
services:
  - mongodb
deploy:
  provider: heroku
   api_key:
    secure: vyEZEnZgxr+/73Xor3A3Zch1+w/+f9YOP3FmYrdLe4v0NwzjDlg//Q96B0Q9CabWc5+zOpF9109GzkDnSq0voIAWINUPDxs/baXFxuztgi4Nj120uH5oaglSXJfPcX1av2jzbZzoDXMSEgje+gplxe7YPmeRRJyoNu/z1NHwqPbV5l4KNicp+E1R9unZFhaH9zyfLD7XLUiwxOB+FbgQTPWP+yNvXqnoMwi9qkxE1mPLSfb1yKkLyksTYBH5w/sGioAZIIxNzKHgUtqZ0SAzIGrQiJzJjRQk9o+JV6/WsGnnhVVeOsZwpEtrLM22vAhq0CkgZ1/zwkpCP7W+tgYJQnvLRPVTJGZElOguPeJCoOn1ReoqGHAMUVOX3B13aG5HrsvP6z5UMhA3ymQrg6IZU/ohDyr9+bLjc/asrhEZjjAV/KQLnSZHd9koV+m65Bf7SGWWkxX2oFComYsFJYhzTidNq3Rc7S4t+vWpeaEiAKL/lI+slXAYzQchDp4ow90Q7ab6dcbFJ4y9Edw4A3Sdr0z+If+mXRUJCobcLvo3Apg8tfGLoQDD4VBC2aSFrb06PdHCR0GcvKZHrgSpqMqhQOZuYcYy73+bscyXHopQ8IpOtDT02Ar+DcgA4e/aTLPRvQIF6xwGFzOaoG3VEAcRIa1Qn/7Hi/G59RR+rSHkO0Q=
  app: pure-oasis-55665
  on:
    repo: Chrolan/node-capstone-csr
